### ISSUE TITLE
numerical instability in v0.2.1?

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/careless#61]
While running a scan of rDW parameters, Careless fails with an error (trimmed err file attached) for two intermediate values in the range. The other runs appear to have completed successfully. This is for the thermolysin benchmark dataset. 

[myoutput_23924812_trimmed_err.txt](https://github.com/Hekstra-Lab/careless/files/9359648/myoutput_23924812_trimmed_err.txt)
[inputs_params.txt](https://github.com/Hekstra-Lab/careless/files/9359649/inputs_params.txt)
[myoutput_23924812_out.txt](https://github.com/Hekstra-Lab/careless/files/9359650/myoutput_23924812_out.txt)

**Comment by kmdalton** [comment]
Thanks, @DHekstra, this problem will most likely be due to the scale distribution's variance getting too small. Let me have a look at the code and recommend a change to test.

**Comment by kmdalton** [comment]
Following up on this -- any luck, @DHekstra?

**Comment by kmdalton** [comment]
I also ran into this issue when merging thermolysin data with the Double-Wilson prior. Anecdotally, the issue was resolved by 
 1) Setting `scale_shift=1e-6` in the variational distribution [here](https://github.com/Hekstra-Lab/careless/blob/8f74451ec8179cbad0f8b604b4af595805e9a4ec/careless/models/merging/surrogate_posteriors.py#L104)
 2) Setting `epsilon=1e-6` in the scale distribution [here](https://github.com/Hekstra-Lab/careless/blob/8f74451ec8179cbad0f8b604b4af595805e9a4ec/careless/models/scaling/nn.py#L10)
 
 Since the minimum acceptable value for these parameters doesn't seem to be the same across data sets, I think I'd like to add an `--epsilon` flag to the CLI. I'll set it to some conservative default like `1e-6` or `1e-7`.

**Comment by kmdalton** [comment]
This was resolved in #62 by adding a command line option controlling the minimum values for variational scale parameters.

**Comment by DHekstra** [comment]
I'm still running into an issue:

``
[myoutput_25775287.out.txt](https://github.com/Hekstra-Lab/careless/files/9491328/myoutput_25775287.out.txt)
[myoutput_25775287.err.txt](https://github.com/Hekstra-Lab/careless/files/9491329/myoutput_25775287.err.txt)
[merge.sh.txt](https://github.com/Hekstra-Lab/careless/files/9491333/merge.sh.txt)

**Comment by kmdalton** [comment]
please provide your input mtz.

**Comment by kmdalton** [comment]
your example doesn't make a single good step. to me the most likely culprit would be nans in the input. this can happen if you have a column that only has a single value. for instance if all the entries in `mtz['PASS']` were zeros, this would lead to a division by zero error when `careless` tries to normalize the data. 

we should change the CLI to do something more graceful, but i think that's a separate issue.

**Comment by DHekstra** [comment]
it's `one_hot.mtz` in `/n/holyscratch01/hekstra_lab/dhekstra/careless-examples/hewl_ssad/progress_w_N/hewl_ssad_fr180`

**Comment by DHekstra** [comment]
Yes, PASS was all zeros for MTZs spanning only the first pass (not surprisingly). It's running now.
